### ISSUE TITLE
[OTHER] Enable more checks in checkstyle

### ISSUE THREAD

**Issue by vil02** [TheAlgorithms/Java#5119]
### What would you like to share?

#5110 introduced checkstyle. The [config file](https://github.com/TheAlgorithms/Java/blob/master/checkstyle.xml) has some of the rules _commented out_. It might a good idea to introduce some of them and discuss why the other ones are not needed in this repository.

## List of checks which should be introduced

Few of the _obvious_ checks, which should be introduced:
- [x] ConstantName (#5139 by @marysiuniq)
- [x] LocalFinalVariableName (#5172 by @CodaBlurd)
- [x] LocalVariableName (#5191 by @cpu-pixel)
- [x] MemberName (#5193 by @cpu-pixel)
- [x] MethodName (#5182 by @CodaBlurd)
- [x] ParameterName (#5196 by @CodaBlurd)
- [x] StaticVariableName (#5173 by @vaibhav9t1)
- [x] TypeName (#5214 by @StarDxxx)
- [x] AvoidStarImport (#5141)
- [x] ModifierOrder (#5132 by @marysiuniq)
- [x] RedundantModifier (#5140)
- [x] EmptyStatement (#5120)
- [x] MultipleVariableDeclarations (#5175 by @vaibhav9t1)
- [x] HideUtilityClassConstructor (#5147)
- [x] ArrayTypeStyle (#5145)
- [x] InvalidJavadocPosition (#5237 by @samuelfac)
- [x] OperatorWrap (#5212 by @StarDxxx)
- [x] ParenPad (#5226 by @samuelfac)
- [x] EqualsHashCode (#5157 by @CodaBlurd)
- [x] InnerAssignment (#5162 by @CodaBlurd)
- [x] FinalClass (#5154  by @CodaBlurd)
- [x] MissingSwitchDefault (#5179 by @BamaCharanChhandogi)
- [x] NeedBraces (#5227 by @samuelfac)
- [x] AvoidNestedBlocks (#5228 by @samuelfac)
- [x] WhitespaceAround (#5241)
- [x] TodoComment (#5785 by @nishchalgv1)

(@siriak, @BamaCharanChhandogi feel free to edit the list above)

## How to contribute

1. select one _check_ form the list above such that no one else is working on (and is not done yet),
2. write a comment "Hey, I am working on `XYZ`", where `XYZ` is your selected check,
3. in your fork, please create a branch like enable_XYZ,
4. uncomment the `XYZ` check in the [`checkstyle.xml`](https://github.com/TheAlgorithms/Java/blob/master/checkstyle.xml),
5. run [`mvn checkstyle:check`](https://github.com/TheAlgorithms/Java/blob/7a42f68b66dfc7a53d67125f9685a2db0a5e2dd9/.github/workflows/build.yml#L33) and fix all of the errors - please keep your changes _minimal_,
6. commit your changes with a message like "style: enable `XYZ` in checkstyle",
7. create a pull-request and mention this issue by writing something like "Related to #5119".

**Comment by vil02** [comment]
I will work on `EmptyStatement`.

**Comment by marysiuniq** [comment]
Hey, I will be working on `ModifierOrder`.

**Comment by marysiuniq** [comment]
Now, I will be working on `ConstantName`.

**Comment by vil02** [comment]
I will work on `RedundantModifier`.

**Comment by vil02** [comment]
I will slowly work on `AvoidStarImport`.

**Comment by vil02** [comment]
I will work on `ArrayTypeStyle`.

**Comment by vil02** [comment]
I will work on `HideUtilityClassConstructor`.

**Comment by vil02** [comment]
@siriak, @BamaCharanChhandogi I have extended the list of _obvious_ checks. Please have a look and edit the list if needed.

**Comment by CodaBlurd** [comment]
Hi, I will be working on FinalClass

**Comment by CodaBlurd** [comment]
I will work on EqualsHashCode.

**Comment by CodaBlurd** [comment]
I will work on InnerAssignment.

**Comment by CodaBlurd** [comment]
I will work on LocalFinalVariableName.

**Comment by vaibhav9t1** [comment]
Hey, I will work StaticVariableName.

**Comment by vaibhav9t1** [comment]
Hi, I will work on MultipleVariableDeclarations.

**Comment by BamaCharanChhandogi** [comment]
I will work on `MissingSwitchDefault`

**Comment by vaibhav9t1** [comment]
Hey, I will work on TypeName.

**Comment by CodaBlurd** [comment]
I will work on MethodName.

**Comment by SAIVARDHAN15** [comment]
Hey, I'll be working on TypeName.

**Comment by cpu-pixel** [comment]
I'll be working on `MemberName`.

**Comment by CodaBlurd** [comment]
I will work on ParameterName.

**Comment by StarDxxx** [comment]
I will work on .`OperatorWrap`

**Comment by StarDxxx** [comment]
I will work on .`TypeName`.

**Comment by vil02** [comment]
> `WhitespaceAround` it conflicts with `clang-format`. When I create the spaces clang-format undoes it and causes an error in the checkstyle.

Please have a look at #5241.

**Comment by FishmmansCavalcante** [comment]
I will work on enabling the `FileLength` and `LineLength` checks in the `checkstyle.xml` file.

**Comment by FishmmansCavalcante** [comment]
I will work on enabling the `TodoComment` check in the `checkstyle.xml` file.

**Comment by adityasarfare** [comment]
Hey Can I work on something ?

**Comment by siriak** [comment]
@adityasarfare sure, see what checks are disabled with todo and feel free to enable them one-by-one https://github.com/TheAlgorithms/Java/blob/master/checkstyle.xml

**Comment by vrp0211** [comment]
> Hi,let me know if there is anything i can contribute to on this issue?

picking NoWhitespaceAfter

**Comment by vrp0211** [comment]
Hey, I am working on NoWhitespaceAfter

**Comment by vrp0211** [comment]
> Hey, I am working on NoWhitespaceAfter

Looks like NoWhitespaceAfter is conflicting with clang-format missed the earlier comment , closing the [PR](https://github.com/TheAlgorithms/Java/pull/5442)

**Comment by Brijeshthummar02** [comment]
Hey, I am working on TodoComment.

**Comment by tanishkagupta27** [comment]
Hey, I am working on TodoComment.

**Comment by shamsulalam1114** [comment]
Hey, I am working on MissingSwitchDefault

**Comment by hrishi0902** [comment]
Hey, I am working on #5241 WhitespaceAround

**Comment by hrishi0902** [comment]
Hey, I am working on `WhitespaceAround`

**Comment by ananyadhagat** [comment]
Hey, I am working on TodoComment

**Comment by nishchalgv1** [comment]
Hey, I am working on ### TodoComment

**Comment by nishchalgv1** [comment]
Hey, I am working on **TodoComment**

**Comment by vil02** [comment]
@BamaCharanChhandogi, @CodaBlurd, @StarDxxx, @cpu-pixel, @marysiuniq, @nishchalgv1, @samuelfac, @vaibhav9t1: we did it! We not only improved the quality of the existing code, but also of all of the future code. Thanks for the effort!

@siriak, @BamaCharanChhandogi, @alxkm: I will close this issue as _done_, since the remaindering checks require some more discussion.
