### ISSUE TITLE
[OTHER] Cleanup classes with very strange design

### ISSUE THREAD

**Issue by vil02** [TheAlgorithms/Java#5164]
### What would you like to share?

There are probably many classes in this repository, which have some strange design - we should update all of them. I think we can start with cleaning up these:

## List of the classes needing redesign:
- [ ] `AllPathsFromSourceToTarget`
- [x] `ArrayCombination` (#5181 by @yuvashreenarayanan3)
- [x] `Combination`
- [ ] `ColumnarTranspositionCipher`
- [x] `StringMatchFiniteAutomata` (#5222 by @samuelfac)
- [x] `LetterCombinationsOfPhoneNumber` (#5221 by @samuelfac)

(@siriak, @BamaCharanChhandogi feel free to edit the list above)

## How to contribute

1. select one class form the list above such that no one else is working on (and is not done yet),
2. write a comment "Hey, I am working on `XYZ`", where `XYZ` is your selected class,
3. in your fork, please create a branch like `cleanup_XYZ`,
4. make your changes and create a pull-request, in which you mention this issue by writing something like "Related to #(this issue number)". Please make sure that you add all necessary tests. If possible, prefer _parametrized tests_.

Also feel free to suggest a class, which should be added to the list above.

**Comment by yuvashreenarayanan3** [comment]
Hey, I am working on "ArrayCombination"

**Comment by JeysiStrokk** [comment]
Hello I´m new here and I would like to help !!!

**Comment by vil02** [comment]
> Hello I´m new here and I would like to help !!!

@JeysiStrokk would you like to work on `AllPathsFromSourceToTarget`?

**Comment by JeysiStrokk** [comment]
Someone can explain me how can I send a pull request ? I have redesign the class "AllPathsFromSourceToTarget"

**Comment by AbeTheAmatuer** [comment]
Can I work on "Combination"? I know someone else is supposed to be working on it, but its been over a month and its incomplete.

**Comment by AbeTheAmatuer** [comment]
Can I work on "Combination", or "AllPathsFromSourceToTarget"? I know in the comments people were supposed to have worked on this, but they aren't marked as complete, so if they still need work I'd be happy to work on one of them.

**Comment by siriak** [comment]
@AbeTheAmatuer  Sure, feel free to work on them!

**Comment by AbeTheAmatuer** [comment]
Thanks, I'll work on Combination.

**Comment by AbeTheAmatuer** [comment]
@siriak I did some cleanup for Combination. It was mostly fine, so I just changed the class name to, "CombinationGenerator", added some comments and changed a variable name for accuracy. I made a PR.

**Comment by vil02** [comment]
@AbeTheAmatuer please have a look at:
- #5223,
- #5224,
- #5225,

by @samuelfac - these PR are in the stage _almost to be merged_. I am not sure if @samuelfac is planning to continue to work on them - it would be a pity if not..

**Comment by AbeTheAmatuer** [comment]
@vil02 Ok, I'll try my best

**Comment by Dileepkumar18311** [comment]
Hey, I am working on Combination

**Comment by adityasarfare** [comment]
Hey, can I help and Contribute in something ?

**Comment by adityasarfare** [comment]
hey im working on AllPathsFromSourceToTarget

**Comment by TarunVishwakarma1** [comment]
Hey! I'm working on ColumnarTranspositionCipher

**Comment by vil02** [comment]
> can you please tell me if you have any specific requirement in mind.

#5223 is a good place to look at. A straightforward implementation with reasonable tests, should be good enough.

**Comment by TarunVishwakarma1** [comment]
Sure, I'll start working on this 😊😊

**Comment by TarunVishwakarma1** [comment]
Yes, sure go ahead.

**Comment by SAIVARDHAN15** [comment]
thanks mate!
I will be working on "ColumnarTranspositionCipher"

**Comment by Anurag127001** [comment]
Hey, I am working on "AllPathsFromSourceToTarget"

**Comment by Anurag127001** [comment]
I will be working on "AllPathsFromSourceToTarget"

**Comment by SAIVARDHAN15** [comment]
hey @Anurag127001!
are you working on "AllPathsFromSourceToTarget", if you need any help, I happy to do so.

**Comment by lorduke22** [comment]
Hello, I am working on "Combination"

**Comment by Soumayadip937** [comment]
@siriak & @SAIVARDHAN15  is ColumnarTranspositionCipher available? I am new to open source combination, can I start work with this?

**Comment by SAIVARDHAN15** [comment]
hey there @Soumayadip937, ColumnarTranspositionCipher is alreday closed. You may checkout other open issues.
